### ISSUE TITLE
eego sports - Use of new amplifiers without license files

### ISSUE THREAD

**Issue by evko6688** [mne-tools/mne-cpp#481]
@johaenns
Is it possible to use (or change the code accordingly) the new eego amplifiers (eego sports TM), because company told me they longer provide the licensce files?

**Comment by LorenzE** [comment]
From what I remember the license file is not needed by our MNE Scan plugin implementation, but by the SDK itself. Since the SDK is provided by the ANT guys, I guess the newest SDK should work without the license files now? 

Have you tried to compile the plugin with the newest SDK and connect to the amplifier without the license files present in `C:\Users\Username\Documents\Eego`?

@johaenns Which SDK version do you use? Also, do you need to use the license files?

**Comment by johaenns** [comment]
I'm using SDK version 1.3.19, which doesn't need a license file.

**Comment by LorenzE** [comment]
@evko6688 I think I saw the same SDK version on your PC, right?

**Comment by LorenzE** [comment]
Were you able to get it to run without the license files?

**Comment by evko6688** [comment]
Yes it was the same SDK version. And I have no idea why, but no both new amplifiers work smoothly as well (no "nothing connected" error).
